export const ADD_LOG_DATA = "ADD_LOG_MESSAGE";

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE";

export const FETCH_ITEM_REQUEST = "FETCH_ITEM_REQUEST";
export const FETCH_ITEM_SUCCESS = "FETCH_ITEM_SUCCESS";
export const FETCH_ITEM_FAILURE = "FETCH_ITEM_FAILURE";

export const SEARCH_SKU_REQUEST = "SEARCH_SKU_REQUEST";
export const SEARCH_SKU_SUCCESS = "SEARCH_SKU_SUCCESS";
export const SEARCH_SKU_FAILURE = "SEARCH_SKU_FAILURE";

export const FILTER_PRODUCT_REQUEST = "FILTER_PRODUCT_REQUEST";
export const FILTER_PRODUCT_SUCCESS = "FILTER_PRODUCT_SUCCESS";
export const FILTER_PRODUCT_FAILURE = "FILTER_PRODUCT_FAILURE";
